[op][ups] Use shlex instead of pipes
:Release Notes:
On hosts with python-3.13 or with python-native upgraded to 3.13 in:
https://git.openembedded.org/openembedded-core/commit/?id=0b49c9aa31279ecda565cc66b63d1d61723b37b8

:Detailed Notes:
fixes:
http://gecko.lge.com:8000/Errors/Details/999925

BUILD_TARGETS are v8_snapshot_clang_x64/mksnapshot
Traceback (most recent call last):
  File "tmp/work/x86_64-linux/mksnapshot-cross-x86_64/108.0.5359.217-32/git/depot_tools/gn.py", line 17, in <module>
    import gclient_paths
  File "tmp/work/x86_64-linux/mksnapshot-cross-x86_64/108.0.5359.217-32/git/depot_tools/gclient_paths.py", line 13, in <module>
    import gclient_utils
  File "tmp/work/x86_64-linux/mksnapshot-cross-x86_64/108.0.5359.217-32/git/depot_tools/gclient_utils.py", line 19, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Original commit message:
Importing pipes gets a DeprecationWarning. shlex.quote is equivalent to
pipes.quote. Use that instead.

Bug: 1522874
Change-Id: I18b8598f2e961d58ba71d886921bda9d9ad956ca
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/5243707
Reviewed-by: Joanna Wang <jojwang@chromium.org>
Auto-Submit: Gavin Mak <gavinmak@google.com>
Commit-Queue: Joanna Wang <jojwang@chromium.org>
Reviewed-on: http://gpro.lge.com/c/webosose/chromium120/+/453196
Reviewed-by: Joonhyung Hwang <joonhyung.hwang@lge.com>
Tested-by: Joonhyung Hwang <joonhyung.hwang@lge.com>
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>