[op][upsable][build] Fix build with gcc-13
:Release Notes:

:Detailed Notes:
Fixes:

http://gecko.lge.com:8000/Errors/Details/772501

FAILED: obj/third_party/ruy/ruy_instrumentation/instrumentation.o
ccache x86_64-webos-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/120.0.6099.269-pro.2/recipe-sysroot -MMD -MF obj/third_party/ruy/ruy_instrumentation/instrumentation.o.d -DRUY_PROFILER -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_NETWORK_ERROR_PAGE_CONTROLLER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DENABLE_NETCAST_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DENABLE_WEBM_AUDIO_CODECS=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DUSE_SINGLE_WINDOW_MODE=1 -DUSE_NEVA_CHROME_EXTENSIONS=1 -DWEBOS_SUBMISSION_NUMBER=2 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_LTTNG=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../git/src -Igen -I../../git/src/third_party/ruy/src -Wno-unused-variable -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -fno-ident -fno-strict-aliasing -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -O2 -fdata-sections -ffunction-sections -fno-math-errno -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wno-narrowing -Wno-class-memaccess -std=gnu++2a -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc -o obj/third_party/ruy/ruy_instrumentation/instrumentation.o
In file included from ../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc:16:
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.h:55:8: error: 'string' in namespace 'std' does not name a type
   55 |   std::string Formatted() const;
      |        ^~~~~~
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.h:23:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   22 | #include <vector>
  +++ |+#include <string>
   23 | #endif
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.h: In member function 'void ruy::profiler::detail::ThreadStack::Push(Args ...)':
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.h:147:7: error: there are no arguments to 'abort' that depend on a template parameter, so a declaration of 'abort' must be available [-fpermissive]
  147 |       abort();
      |       ^~~~~
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.h:147:7: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc: In member function 'bool ruy::profiler::Label::operator==(const ruy::profiler::Label&) const':
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc:34:12: error: 'string' is not a member of 'std'
   34 |   if (std::string(format_) != std::string(other.format_)) {
      |            ^~~~~~
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc:21:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   20 | #include <cstring>
  +++ |+#include <string>
   21 |
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc:34:36: error: 'string' is not a member of 'std'
   34 |   if (std::string(format_) != std::string(other.format_)) {
      |                                    ^~~~~~
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc:34:36: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc: At global scope:
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc:48:6: error: 'string' in namespace 'std' does not name a type
   48 | std::string Label::Formatted() const {
      |      ^~~~~~
../../git/src/third_party/ruy/src/ruy/profiler/instrumentation.cc:48:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
   48 | std::string Label::Formatted() const {
      | ^~~

and
../../git/src/ui/events/ozone/evdev/input_device_settings_evdev.h:15:12: error: 'DomCode' has not been declared
../../git/src/ui/events/ozone/evdev/input_device_settings_evdev.h:15:20: error: found ':' in nested-name-specifier, expected '::'
../../git/src/ui/events/ozone/evdev/input_device_settings_evdev.h:88:15: error: 'DomCode' was not declared in this scope
../../git/src/ui/events/ozone/evdev/input_device_settings_evdev.h:88:22: error: template argument 1 is invalid
../../git/src/ui/events/ozone/evdev/input_device_settings_evdev.h:88:22: error: template argument 2 is invalid
../../git/src/ui/events/ozone/evdev/input_device_settings_evdev.h:88:8: error: '<expression error>' in namespace 'std' does not name a type

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield

Change-Id: I9ad64589cc33624a9400196e47b4ef65aebfbec8
Originally-Reviewed-on: http://gpro.lge.com/c/webosose/chromium108/+/351386
Reviewed-on: http://gpro.lge.com/c/webosose/chromium120/+/391651
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Minsu Kim <minsu0.kim@lge.com>
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>
(cherry picked from commit 5014f466bc662ec79b1ddd675567493f5eb4d72d)
Reviewed-on: http://gpro.lge.com/c/webosose/chromium120/+/407570
Tested-by: Donghyun Kim <donghyun11.kim@lge.com>