[op][n_upsable][build] Build fix with permissions code because of missing dependency
:Release Notes:
Fixed failing on finding permission_status.mojom.h

:Detailed Notes:
This patch is trying to below compile errors

| In file included from ../../git/src/neva/browser_service/browser/userpermission_service_impl.cc:17:
| In file included from ../../git/src/neva/browser_service/browser/userpermission_service_impl.h:23:
| In file included from ../../git/src/neva/app_runtime/browser/permissions/permission_prompt.h:10:
| In file included from ../../git/src/components/permissions/permission_prompt.h:12:
| In file included from ../../git/src/components/permissions/permission_ui_selector.h:9:
| In file included from ../../git/src/components/permissions/permission_request.h:15:
| ../../git/src/components/permissions/permission_request_data.h:11:10: fatal error: 'third_party/blink/public/mojom/permissions/permission_status.mojom.h' file not found
|    11 | #include "third_party/blink/public/mojom/permissions/permission_status.mojom.h"
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And
| In file included from ../../git/src/neva/pal_service/webos/proxy_setting_delegate_webos.cc:17:
| In file included from ../../git/src/neva/pal_service/webos/proxy_setting_delegate_webos.h:22:
| In file included from ../../git/src/neva/pal_service/public/proxy_setting_delegate.h:21:
| In file included from ../../git/src/content/public/browser/content_browser_client.h:35:
| In file included from ../../git/src/content/public/browser/file_system_access_permission_context.h:11:
| ../../git/src/content/public/browser/file_system_access_permission_grant.h:14:10: fatal error: 'third_party/blink/public/mojom/permissions/permission_status.mojom-forward.h' file not found
|    14 | #include "third_party/blink/public/mojom/permissions/permission_status.mojom-forward.h"
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

permission_status.mojom.h file is generated by
third_party/blink/public/mojom:mojom_platform but deps is missing.

browser_service needs to have deps to app_runtime/browser
pal_service needs to have deps to content/public/browser

But having above deps it makes dependency cycle that means it has
wrong design and it needs to refactor.

In this patch for the temporary fix, add deps directly to
third_party/blink/public/mojom:mojom_platform to resolve compile error.

:Testing Performed:
Build completed.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-30268] Fix compile error

Change-Id: Ie800df3a93f891a727b958e76b118e9832e494f7
Reviewed-on: http://gpro.lge.com/c/webosose/chromium120/+/423819
Reviewed-by: Jeonghee27 Ahn <jeonghee27.ahn@lge.com>
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>
Tested-by: Jeonghee27 Ahn <jeonghee27.ahn@lge.com>
Blink-Build: Wanchang Ryu <wanchang.ryu@lge.com>