[op][n_upsable][media] Fix sequence checks in NEVA input controller code
:Release Notes:
Fix development asserts in NEVA specific media code.

:Detailed Notes:
DCHECK-guarded code sequences that are NEVA specific were not updated
to use sequence checkers.

DCHECK_CALLED_ON_VALID_THREAD(owning_thread_);
was added twice in:

  commit f9bebd4b90d6ec90e01f65d5b23b6bea2294af9e
  Author: Minsu Kim <minsu0.kim@lge.com>
  Date:   Wed Aug 23 18:18:35 2023 +0900

    [op][n_ups][build][base] Snapshot of webos-pro/chromium release changes (branch: ose/chromium108)

but there is no owning_thread_ since:
https://chromium.googlesource.com/chromium/src/+/6c82dca1d95c8536f1a4949cc28d0aa542e9667a

Fixes:
http://gecko.lge.com:8000/Errors/Details/783278

FAILED: obj/services/audio/audio/input_controller.o
ccache  ../../git/src/third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/services/audio/audio/input_controller.o.d -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_MEDIA=1 -DUSE_GAV=1 -DUSE_NEVA_MEDIA_PLAYER_CAMERA=1 -DUSE_NEVA_BROWSER_SERVICE=1 -DUSE_WEBRISK_SERVICE=1 -DUSE_WEBRISK_DATABASE=1 -DENABLE_PINCH_TO_ZOOM=1 -DUSE_NEVA_PUNCH_HOLE=1 -DUSE_NEVA_V4L2_CODEC=1 -DENABLE_WEBM_AUDIO_CODECS=1 -DUSE_GST_MEDIA=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DUSE_SINGLE_WINDOW_MODE=1 -DWEBOS_SUBMISSION_NUMBER=23 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_WEBOS_CODEC=1 -DUSE_LTTNG=1 -DDCHECK_ALWAYS_ON=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-16-init-6578-g0d30e92f-2\" -DCR_SYSROOT_KEY=20220331T153654Z-0 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSE_NEON -DUSE_PULSEAUDIO -DDLOPEN_PULSEAUDIO -DUSE_WEBOS_AUDIO=1 -DUSE_ALSA -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBP_EXTERN=extern -DUSE_EGL -DVK_USE_PLATFORM_WAYLAND_KHR -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 -DHAVE_PTHREAD -DLEVELDB_PLATFORM_CHROMIUM=1 -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DLOGGING_INSIDE_WEBRTC -I../../git/src -Igen -I../../git/src/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../git/src/third_party/libwebp/src/src -I../../git/src/third_party/khronos -I../../git/src/gpu -I../../git/src/third_party/vulkan-deps/vulkan-headers/src/include -Igen/third_party/dawn/include -I../../git/src/third_party/dawn/include -I../../git/src/third_party/libyuv/include -I../../git/src/third_party/jsoncpp/source/include -I../../git/src/third_party/abseil-cpp -I../../git/src/third_party/boringssl/src/include -I../../git/src/third_party/protobuf/src -Igen/protoc_out -I../../git/src/third_party/libwebm/source -I../../git/src/third_party/skia -I../../git/src/third_party/wuffs/src/release/c -I../../git/src/third_party/vulkan/include -I../../git/src/third_party/mesa_headers -I../../git/src/third_party/icu/source/common -I../../git/src/third_party/icu/source/i18n -I../../git/src/third_party/leveldatabase -I../../git/src/third_party/leveldatabase/src -I../../git/src/third_party/leveldatabase/src/include -I../../git/src/third_party/libaom/source/libaom -I../../git/src/third_party/ced/src -I../../git/src/net/third_party/quiche/overrides -I../../git/src/net/third_party/quiche/src/quiche/common/platform/default -I../../git/src/net/third_party/quiche/src -Igen/net/third_party/quiche/src -I../../git/src/third_party/webrtc_overrides -I../../git/src/third_party/webrtc -Igen/third_party/webrtc -Wno-unused-variable -Wall -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../git/src/tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -mbranch-protection=standard --target=aarch64-linux-gnu -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -g0 -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-23/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-23/recipe-sysroot/usr/lib/glib-2.0/include -DPROTOBUF_ALLOW_DEPRECATED=1 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-23/recipe-sysroot/usr/include/nss3 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-23/recipe-sysroot/usr/include/nspr -std=c++20 -Wno-trigraphs -fno-exceptions -fno-rtti --sysroot=../../recipe-sysroot -fvisibility-inlines-hidden -Wno-deprecated-declarations      -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-23/recipe-sysroot/usr/include/c++/v1       -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-23/recipe-sysroot/usr/include/cbe     -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-23/recipe-sysroot/usr/include/cbe/gmp     -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-23/recipe-sysroot/usr/include/media-resource-calculator-clang   -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  -c ../../git/src/services/audio/input_controller.cc -o obj/services/audio/audio/input_controller.o
../../git/src/services/audio/input_controller.cc:374:33: error: unknown type name 'owning_thread_'
  DCHECK_CALLED_ON_VALID_THREAD(owning_thread_);
                                ^
:Testing Performed:
Build with dcheck_always_on=true

:QA Notes:
Test-cases: N/A

:Issues Addressed:
[WRQ-19408] Port : [op][n_upsable][media] Fix sequence checks in NEVA input controller code
[WRP-16526] [M110][Bug]Check failed: sequence_checker_.CalledOnValidSequence()

Change-Id: I902cb04d90d021433be9dc691df66a39cc76f4fe
Originally-Reviewed-on: http://gpro.lge.com/c/webos-pro/chromium/+/359287
Reviewed-on: http://gpro.lge.com/c/webosose/chromium108/+/393560
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>
Tested-by: Jose Dapena Paz <j.dapena@lgepartner.com>
Reviewed-on: http://gpro.lge.com/c/webosose/chromium120/+/407745
Tested-by: Donghyun Kim <donghyun11.kim@lge.com>